[package]
name = "deputy"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
deputy-core = { version = "0.1.0", path = "../deputy-core" }
proc-macro2 = "^1.0.36"
syn = "2.0.39"
quote = "^1.0"
tap = "1.0.1"
tracing = "0.1.40"
async-trait = "0.1.74"
